name = "computron"
type = "webpack"
workers_dev = true
route = "*computron.laspruca.nz/*"
zone_id = "98b5c5ac07aaffb82af6a983906951dc"
account_id = "10efb33f54be2b4b7065b90921d9ebef"

[site]
bucket = "./build"
entry-point = "./workers-site"
